# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRFwqMzkty0XW7uEADmnJKtz15tbPlKC

#Between Fall 2021 and Fall 2025 (time window), how did the freshman admit rate for Asian applicants at UC Santa Cruz (population of interest) change, measured in percentage point difference (metric being measured)?
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ============================================================
# PAGE SETUP
# ============================================================

st.set_page_config(
    page_title="UCSC Admissions Dashboard",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
.block-container {
    padding-top: 0.7rem;
    padding-bottom: 0rem;
    padding-left: 2rem;
    padding-right: 2rem;
    max-width: 100%;
}

h1 {
    font-size: 1.9rem !important;
    margin-bottom: 0rem !important;
}

[data-testid="stMetric"] {
    padding: 2px 8px;
}

[data-testid="stMetricValue"] {
    font-size: 1.55rem;
}

#MainMenu {
    visibility: hidden;
}

footer {
    visibility: hidden;
}
</style>
""", unsafe_allow_html=True)


# ============================================================
# LOAD DATA
# ============================================================

DATA_FILE = (
    Path(__file__).parent /
    "uc_admissions_summary_by_ethnicity.csv"
)

@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

try:
    df = load_data()
except Exception as e:
    st.error("Could not load dataset.")
    st.exception(e)
    st.stop()


# ============================================================
# CLEAN DATA
# ============================================================

df["fall_term"] = pd.to_numeric(
    df["fall_term"],
    errors="coerce"
)

df["n"] = pd.to_numeric(
    df["n"],
    errors="coerce"
)

df["campus"] = (
    df["campus"]
    .astype(str)
    .str.strip()
)

df["ethnicity"] = (
    df["ethnicity"]
    .astype(str)
    .str.strip()
)

df["entrant_level"] = (
    df["entrant_level"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df["count_type"] = (
    df["count_type"]
    .astype(str)
    .str.strip()
)


# ============================================================
# HEADER
# ============================================================

st.title("🎓 UC Santa Cruz Freshman Admissions")

st.caption(
    "Interactive analysis of freshman admission rates by ethnicity"
)


# ============================================================
# INTERACTIVE CONTROLS
# ============================================================

filter1, filter2, filter3 = st.columns([1.2, 1.2, 2])

with filter1:

    campus = st.selectbox(
        "Campus",
        sorted(df["campus"].dropna().unique()),
        index=sorted(
            df["campus"].dropna().unique()
        ).index("Santa Cruz")
    )

with filter2:

    ethnicity_options = sorted(
        df["ethnicity"].dropna().unique()
    )

    default_ethnicity = (
        ethnicity_options.index("Asian")
        if "Asian" in ethnicity_options
        else 0
    )

    ethnicity = st.selectbox(
        "Ethnicity",
        ethnicity_options,
        index=default_ethnicity
    )

with filter3:

    year_range = st.slider(
        "Fall term range",
        min_value=int(df["fall_term"].min()),
        max_value=int(df["fall_term"].max()),
        value=(2021, 2025),
        step=1
    )


start_year, end_year = year_range


# ============================================================
# FILTER DATA
# ============================================================

filtered = df[
    (df["entrant_level"] == "freshman")
    & (df["campus"] == campus)
    & (df["ethnicity"] == ethnicity)
    & (df["fall_term"].between(
        start_year,
        end_year
    ))
    & (df["count_type"].isin(
        ["App", "Adm"]
    ))
].copy()


# ============================================================
# SUMMARY
# ============================================================

summary = filtered.pivot_table(
    index="fall_term",
    columns="count_type",
    values="n",
    aggfunc="sum"
).reset_index()


if (
    summary.empty
    or "App" not in summary.columns
    or "Adm" not in summary.columns
):

    st.warning(
        "No admissions data is available "
        "for this selection."
    )

    st.stop()


summary["admit_rate"] = (
    summary["Adm"] /
    summary["App"]
) * 100

summary["admit_rate"] = (
    summary["admit_rate"]
    .round(2)
)

summary = summary.sort_values(
    "fall_term"
)


# ============================================================
# START AND END VALUES
# ============================================================

first = summary.iloc[0]
last = summary.iloc[-1]

actual_start_year = int(
    first["fall_term"]
)

actual_end_year = int(
    last["fall_term"]
)

start_rate = first["admit_rate"]
end_rate = last["admit_rate"]

pp_change = (
    end_rate - start_rate
)

start_apps = first["App"]
end_apps = last["App"]

start_admits = first["Adm"]
end_admits = last["Adm"]


if start_apps != 0:

    applicant_growth = (
        (end_apps / start_apps) - 1
    ) * 100

else:

    applicant_growth = 0


if start_admits != 0:

    admit_growth = (
        (end_admits / start_admits) - 1
    ) * 100

else:

    admit_growth = 0


# ============================================================
# KPI CARDS
# ============================================================

k1, k2, k3, k4, k5 = st.columns(5)

k1.metric(
    f"{actual_start_year} Admit Rate",
    f"{start_rate:.2f}%"
)

k2.metric(
    f"{actual_end_year} Admit Rate",
    f"{end_rate:.2f}%"
)

k3.metric(
    "Rate Change",
    f"{pp_change:+.2f} pp"
)

k4.metric(
    "Applicant Growth",
    f"{applicant_growth:+.1f}%"
)

k5.metric(
    "Admit Growth",
    f"{admit_growth:+.1f}%"
)


# ============================================================
# CHARTS
# ============================================================

left, right = st.columns([1.2, 1])


# ------------------------------------------------------------
# LINE CHART
# ------------------------------------------------------------

with left:

    st.markdown("#### Admit Rate Trend")

    fig1, ax1 = plt.subplots(
        figsize=(6.5, 2.7)
    )

    ax1.plot(
        summary["fall_term"],
        summary["admit_rate"],
        marker="o",
        linewidth=2
    )

    ax1.set_ylabel("Admit Rate (%)")

    ax1.set_xlabel("Fall Term")

    ax1.set_xticks(
        summary["fall_term"]
    )

    min_rate = max(
        0,
        summary["admit_rate"].min() - 10
    )

    max_rate = min(
        100,
        summary["admit_rate"].max() + 10
    )

    ax1.set_ylim(
        min_rate,
        max_rate
    )

    ax1.grid(
        axis="y",
        alpha=0.25
    )

    for year, rate in zip(
        summary["fall_term"],
        summary["admit_rate"]
    ):

        ax1.annotate(
            f"{rate:.1f}%",
            (year, rate),
            xytext=(0, 6),
            textcoords="offset points",
            ha="center",
            fontsize=8
        )

    fig1.tight_layout()

    st.pyplot(
        fig1,
        use_container_width=True
    )

    plt.close(fig1)


# ------------------------------------------------------------
# BAR CHART
# ------------------------------------------------------------

with right:

    st.markdown("#### Applicants vs. Admits")

    fig2, ax2 = plt.subplots(
        figsize=(6, 2.7)
    )

    x = list(
        range(len(summary))
    )

    width = 0.36

    ax2.bar(
        [i - width / 2 for i in x],
        summary["App"],
        width,
        label="Applicants"
    )

    ax2.bar(
        [i + width / 2 for i in x],
        summary["Adm"],
        width,
        label="Admits"
    )

    ax2.set_xticks(x)

    ax2.set_xticklabels(
        summary["fall_term"]
    )

    ax2.set_xlabel(
        "Fall Term"
    )

    ax2.set_ylabel(
        "Students"
    )

    ax2.legend(
        frameon=False,
        fontsize=8
    )

    ax2.grid(
        axis="y",
        alpha=0.2
    )

    fig2.tight_layout()

    st.pyplot(
        fig2,
        use_container_width=True
    )

    plt.close(fig2)


# ============================================================
# INTERACTIVE DATA TABLE
# ============================================================

with st.expander(
    "View underlying data"
):

    table = summary.rename(
        columns={
            "fall_term":
                "Fall Term",

            "App":
                "Applicants",

            "Adm":
                "Admits",

            "admit_rate":
                "Admit Rate (%)"
        }
    )

    st.dataframe(
        table,
        use_container_width=True,
        hide_index=True
    )


# ============================================================
# DYNAMIC FINDING
# ============================================================

direction = (
    "increased"
    if pp_change > 0
    else "decreased"
    if pp_change < 0
    else "did not change"
)

st.info(
    f"**Key Finding:** For **{ethnicity} freshman applicants "
    f"at UC {campus}**, the admit rate {direction} from "
    f"**{start_rate:.2f}% in Fall {actual_start_year}** "
    f"to **{end_rate:.2f}% in Fall {actual_end_year}**, "
    f"a change of **{pp_change:+.2f} percentage points**."
)